### ISSUE TITLE
Getting `gopls` to work

### ISSUE THREAD

**Issue by pltrz** [kak-lsp/kak-lsp#210]
Trying to get [`gopls`](https://github.com/golang/go/wiki/gopls) working with kakoune via `kak-lsp`, at least in it's default configuration it didn't work for me. Kind of expected this as it's still alpha, but this issue can also serve as a place to continue to investigate further and eventually get `gopls` working.

example config:
```toml
[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
args = ["serve"]
```

Tried with/without the "serve" parameter.

[A talk on `gopls`](https://youtu.be/5Re6BHEOT_k)
