### ISSUE TITLE
language server (clangd) is started in kakoune's cwd not in root 

### ISSUE THREAD

**Issue by 6he** [kak-lsp/kak-lsp#304]
I have the following configuration for my c++ files.

```toml
[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_flags.txt", "compile_commands.json", "build"]
command = "clangd"
offset_encoding = "utf-8"
args = ["--compile-commands-dir=build"]
```
I'm using cmake and the build directory (containing the compile_command.json file) is in the top directory of my project.
When I open a file in some subdir of my project, my top directory is set as root (I see it in the logs).
But clangd is started in the subdir (I looked it up with pwdx) and the compile_commands.json file is not found.

I'm not sure if this is the intended behavior, but if I remember correctly my configuration used to work before.  

I'm using kakoune version v2020.01.16 (Arch package) and installed kak-lsp from git (using plug.kak).
