### ISSUE TITLE
Spurious warning when using proc macros and rust-analyzer

### ISSUE THREAD

**Issue by dmerejkowsky** [kak-lsp/kak-lsp#445]
Steps to reproduce:

kakoune version: v2020.09.01

rust-analyzer version:dbd0cfb

kak-lsp version: 9.0.0

```rust
// in src/main.rs
use paste::paste;

macro_rules! plop {
    ($name: ident) => {
        paste! {
            let [< _plop_ $name>] = 42 ;
        };
    };
}

fn main() {
    plop!(x);
}
```

```toml
# in Cargo.toml
[package]
name = "foo"
version = "0.1.0"

[dependencies]
paste = "1.0.4"
``` 

```kak
# In kakrc
set-option global lsp_server_configuration rust-analyzer.diagnostics.disabled=["unresolved-proc-macro"]
```

```
:lsp-enable
:lsp-diagnostics

src/main.rs:12:5: warning:proc macro not expanded
````

Maybe there's something wrong with the `lsp_server_configuration` option?

I tried to enable logs for both rust-analyzer and kak-lsp but did not see any relevant info #16

**Comment by dmerejkowsky** [comment]
Found it! Turns out you can *also* set options directly in the kak-lsp.toml file, like this:

```toml
[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"
[language.rust.initialization_options]
diagnostics.disabled = ["unresolved-proc-macro"]
````

**Comment by krobelus** [comment]
This is not specific to Kakoune/kak-lsp. The warning can be reproduced on your example with 

```$
$ rust-analyzer diagnostics src/main.rs
processing crate: foo, module: $PWD/src/main.rs
Diagnostic { message: "proc macro not expanded", range: 388..396, severity: WeakWarning, fix: None, unused: false, code: Some(DiagnosticCode("unresolved-proc-macro")) }

diagnostic scan complete
```

Relevant issues are https://github.com/rust-analyzer/rust-analyzer/issues/7497 and https://github.com/rust-analyzer/rust-analyzer/issues/6448.
So the alternative fix would be to enable proc macro support in rust-analyzer:

```toml
[language.rust.initialization_options]
cargo.loadOutDirsFromCheck = true
procMacro.enable = true
```
