### ISSUE TITLE
Language server is not configured for filetype ``

### ISSUE THREAD

**Issue by InfRandomness** [kak-lsp/kak-lsp#462]
Hi, I'm new to kak and kak-lsp, I'm trying to setup C completion on kak using kak-lsp, however I'm having a few issues : 

I tried doing "kak-lsp -vvvv --session session" in a window and then "kak -s session file.c" + lsp-capabilities (in kak)

the kak-lsp window reported me this : 
```
Feb 23 10:19:54.599 DEBG Language server is not configured for filetype ``, module: kak_lsp::session:80
```

I'm not sure what if I have configured something wrong or if this is a possible bug.

configuration files : 
kakrc : 
```
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(c|cpp|zig) %{
    lsp-enable-window
    lsp-auto-hover-enable
    lsp-auto-signature-help-mode
    lsp-auto-hover-insert-mode-disable
}
```
kak-lsp :
```toml
snippet_support = false
verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd"]
command = "clangd"

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "zls"
```
my environment : 
OS : ArchLinux
kak : Kakoune v2020.09.01
kak-lsp : kak-lsp 9.0.0
clangd : clangd version 11.1.0

Thanks in advance.
