### ISSUE TITLE
Failed to start language server even though it definitely exists

### ISSUE THREAD

**Issue by raiguard** [kak-lsp/kak-lsp#469]
I have been having issues configuring kak-lsp to work with Lua. I downloaded [sumneko's Lua LS](https://github.com/sumneko/lua-language-server) and grabbed the binary from the vscode extension repo, and set up kak-lsp as so:

```toml
[language.lua]
filetypes = ["lua"]
roots = [".git/"]
command = "home/raiguard/.servers/sumneko-lua/bin/lua-language-server"
args = ["-E", "home/raiguard/.servers/sumneko-lua/main.lua"]
```

I enabled kak-lsp on filetype Lua in my kakrc:

```
hook global WinSetOption filetype=(rust|lua) %{
    echo -debug "Enabling LSP for filetype %opt{filetype}"
    lsp-enable-window

    # Other settings are below this point, such as auto_highlight_references and semantic tokens
}
```

However, when I open a Lua file, this error appears:
![image](https://user-images.githubusercontent.com/3515394/111683150-c3159280-87ea-11eb-99e7-61c55470e5c3.png)

I tested the command in my shell manually, and it works perfectly:
![image](https://user-images.githubusercontent.com/3515394/111683338-f35d3100-87ea-11eb-9663-6513fef6fc2f.png)

Any idea what is going on?
