### ISSUE TITLE
Instructions for less/scss css

### ISSUE THREAD

**Issue by lelgenio** [kak-lsp/kak-lsp#473]
`css-languageserver` supports less and scss.

```toml
# This will not work
[language.css]
filetypes = ["css", "less", "scss"]
roots = ["package.json"]
command = "css-languageserver"
args = ["--stdio"]
```

```toml
# This will work
[language.css]
filetypes = ["css"]
roots = ["package.json"]
command = "css-languageserver"
args = ["--stdio"]

[language.less]
filetypes = ["less"]
roots = ["package.json", ".git"]
command = "css-languageserver"
args = ["--stdio"]

[language.scss]
filetypes = ["scss"]
roots = ["package.json", ".git"]
command = "css-languageserver"
args = ["--stdio"]
```
