### ISSUE TITLE
Some semantic tokens are no longer working

### ISSUE THREAD

**Issue by raiguard** [kak-lsp/kak-lsp#494]
As of a few weeks ago, some semantic tokens stopped being shown. I double and triple checked my `kak-lsp.toml` but couldn't find an answer as to why this is. I also updated the configuration format when that changed, but it didn't help anything.

Here is a screenshot of some basic rust code:

![image](https://user-images.githubusercontent.com/3515394/121818267-540dd580-cc43-11eb-9fb9-78a07f32081d.png)

There are multiple things here that aren't colored correctly:
- `Bar` and `Baz` should be cyan (using the `enum` face)
- `derive`, `structopt`, and `allow` should be blue (functions)

Here are some other ones that don't work that aren't pictured:
- I set Rust lifetimes to be colored as operators (red), but they're not being colored
- `==` is not being colored as an operator either
- Macros are not being colored as functions

However, other things, such as `::` and `->` (not pictured here) are colored semantically and they work fine. Function parameters also work fine as well. It's really strange that some are working but some are not.

I checked with vscode and used the `Inspect editor tokens and scopes` command, and rust-analyzer is putting out the correct tokens. There's something going on on the kak-lsp side.

<details><summary>kak-lsp.toml</summary>

```toml
# GENERAL

verbosity = 2

# SEMANTIC TOKENS

[[semantic_tokens]]
token = "comment"
face = "comment"

[[semantic_tokens]]
token = "enum"
face = "module"

[[semantic_tokens]]
token = "enumMember"
face = "enum"

[[semantic_tokens]]
token = "formatSpecifier"
face = "operator"

[[semantic_tokens]]
token = "function"
face = "function"

[[semantic_tokens]]
token = "keyword"
face = "keyword"

[[semantic_tokens]]
token = "lifetime"
face = "enum"

[[semantic_tokens]]
token = "macro"
face = "function"

[[semantic_tokens]]
token = "namespace"
face = "module"

[[semantic_tokens]]
token = "operator"
face = "operator"

[[semantic_tokens]]
token = "parameter"
face = "parameter"

[[semantic_tokens]]
token = "punctuation"
face = "operator"

[[semantic_tokens]]
token = "regexp"
face = "value"

[[semantic_tokens]]
token = "string"
face = "string"

[[semantic_tokens]]
token = "type"
face = "type"

[[semantic_tokens]]
token = "typeParameter"
face = "operator"

[[semantic_tokens]]
token = "variable"
face = "variable"

# LANGUAGES

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json"]
command = "clangd"

[language.lua]
filetypes = ["lua"]
roots = [".git/"]
command = "lua-language-server"
args = ["-E", "/usr/share/lua-language-server/main.lua"]

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"
```

</details>
