### ISSUE TITLE
Log shows `Language server is not initialized`

### ISSUE THREAD

**Issue by Inoshy** [kak-lsp/kak-lsp#497]
I have installed `kak-lsp` successfully with `plug.kak`. I have placed the `kak-lsp.toml` in `~/.config/kak-lsp/kak-lsp.toml`. For the rustlang part it looks like this:
```toml
[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "sh"
args = ["-c", "if command -v rustup >/dev/null; then $(rustup which rls); else rls; fi"]
``` 
However, when I launch kakoune, it doesn't autocomplete or anything, except it only shows warning for unused variables(and stuff like this). So I turned on the logs, and it gave me this output:
```rs
Jun 30 04:29:35.209 DEBG Language server is not initialized, parking request, module: kak_lsp::controller:100
```
The full log is [here](https://pastebin.com/Pd6svYwp)

What am I missing here?
