### ISSUE TITLE
Incorrect configuration sample for Haskell

### ISSUE THREAD

**Issue by RehMaar** [kak-lsp/kak-lsp#586]
I tried to set `formattingProvider` in `kak-lsp.toml`'s `language.haskell` section to another value according to the sample for `haskell-language-server`'s settings:
```toml
[language.haskell.settings.haskell]
# See https://haskell-language-server.readthedocs.io/en/latest/configuration.html
# formattingProvider = "ormolu"
formattingProvider = "brittany"
```
But the changes didn't apply. 

I've managed to fix the issue with this configuration (note the `haskell.` at the beginning of the line):
```toml
[language.haskell.settings.haskell]
# See https://haskell-language-server.readthedocs.io/en/latest/configuration.html
haskell.formattingProvider = "brittany"
```
I found the issue for haskell-lagnuage-server that may be related to the problem: https://github.com/haskell/haskell-language-server/issues/226
