### ISSUE TITLE
`unknown option '->'` error on trying to execute lsp actions with Rust RLS

### ISSUE THREAD

**Issue by xnuk** [kak-lsp/kak-lsp#612]
![image](https://user-images.githubusercontent.com/3071003/162794329-9c5ef4bb-e385-4b08-b06a-3c53b5ea2f0f.png)
![image](https://user-images.githubusercontent.com/3071003/162794365-06ffccc6-40b9-4dc7-9f9e-b61d0da19e27.png)

> `1:2: 'lsp-menu-select': 2:13: 'evaluate-commands': 1:1: 'fail': unknown option '->'`

Using:
- Arch linux x64
- rustc 1.59.0 (9d1b2106e 2022-02-23)
- rls 1.41.0 (362fa39 2022-01-13)
- kak-lsp 12.1.0
- Kakoune v2021.11.08
- `kak-lsp.toml`:
  ```toml
  verbosity = 2
  snippet_support = true

  [server]
  timeout = 1800

  [language.rust]
  filetypes = ['rust']
  roots = ['Cargo.toml', '.git']
  command = 'rls'
  settings_section = 'rust'

  [language.rust.settings.rust]
  settings.rust.clippy_preference = 'on'
  ```

Maybe related: https://github.com/kak-lsp/kak-lsp/blob/b6c1f943370de902134761afcd4fda293632e548/rc/lsp.kak#L179-L191
