### ISSUE TITLE
How to declare nested JSON config?

### ISSUE THREAD

**Issue by eko234** [kak-lsp/kak-lsp#621]
Hi, I'm trying to run the haxe lsp, but I can't replicate the configuration suggested for standalone use of vim, that goes as follows:

```
{
    "languageserver": {
        "haxe": {
            "command": "node",
            "args": ["<path-to-server.js>"],
            "filetypes": ["haxe"],
            "trace.server": "verbose",
            "initializationOptions": {
                "displayArguments": ["build.hxml"]
            },
            "settings": {
                "haxe.executable": "haxe"
            }
        }
    }
}
```

**Comment by krobelus** [comment]
kak-lsp doesn't have explicit separation of `initializationOptions` and `settings`.
We take everything from a single config object (similar to VSCode).
The object is at `[language.haxe.settings.haxe]`. Users can add all settings there.
We only send `initializationOptions` (and `didChangeConfiguratio` IIRC) if there is a `settings_section`.

So this should correctly communicate `displayArguments`:

```toml
[language.haxe]
filetypes = ["haxe"]
roots = [".git", ".hg"]
command = "node"
args = ["path/to/haxe-language-server/bin/server.js"]
settings_section = "haxe"
[language.haxe.settings.haxe]
displayArguments = "build.hxml"
```

About the executable setting, I'm not sure (I'd need to check VSCode or Vim LSP logs to be sure).
I can think of three possible options, but neither seems to work.

```toml
executable = "path/to/haxe"
haxe.executable = "path/to/haxe"
"haxe.executable" = "path/to/haxe"
```
