### ISSUE TITLE
`kak-lsp` doesn't always send `workspace/didChangeConfiguration` server configuration options

### ISSUE THREAD

**Issue by razcore-rad** [kak-lsp/kak-lsp#654]
I noticed this only for `pyls`, configuration but might be more general.

From the log, seems that at some point `kak-lsp` stops sending the `initialize` `jsonrpc` method.

This means that `pyls` stops using the custom configuration options and reverts to defaults.

---

### `kak-lsp.toml` relevant section

```toml
[language.python]
filetypes = ["python"]
roots = [".git", "requirements.txt", "setup.py", "*.py"]
command = "pylsp"
workaround_server_sends_plaintext_labeled_as_markdown = true
settings_section = "_"
[language.python.settings._]
pylsp.configurationSources = ["flake8"]
pylsp.plugins.pycodestyle.enabled = false
pylsp.plugins.mccabe.enabled = false
pylsp.plugins.pyflakes.enabled = false
pylsp.plugins.flake8.enabled = true
pylsp.plugins.flake8.ignore = ["F821", "F722"]
pylsp.plugins.flake8.maxLineLength = 120
pylsp.plugins.black.line_length = 120
```

---

[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10145960/kak-lsp.log)

**Comment by krobelus** [comment]
I don't see a problem related to `initialize`.
This method is sent twice, both times with your custom configuration.
However there's a panic in your log, which I just fixed in c85c3e66e97a2fd2a14270df693bb76d0ec9c87d.
The panic is the reason for restarting the language server. Maybe that caused the issue although it should really not.
Let me know if it still reproduces / if you have steps to reproduce.

**Comment by razcore-rad** [comment]
Thanks, I'll get the update and check back if the problem persists.

**Comment by razcore-rad** [comment]
I haven't seen `pyls` losing configuration since the update so I'll close this issue for now. If anything changes I'll reopen.

**Comment by razcore-rad** [comment]
So something still happens where `pylsp` doesn't get configure correctly at times. So now because of the panic doesn't happen any more and the server isn't restarted it seems like the server configuration isn't reset in the middle of work, but instead it doesn't get configured at the start of the session at times.

This shows the configuration being default (e.g. ignoring my custom `maxLineLength`:

![image](https://user-images.githubusercontent.com/1177508/205487922-30982769-56f1-4913-b20c-91b9eb9693fb.png)

[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10148348/kak-lsp.log)

Might this be a `pylsp` problem instead?

**Comment by razcore-rad** [comment]
I looked at #655 and I see `kak-lsp` should send `workspace/didChangeConfiguration`which is missing in the log above. On the other hand this is a log where `pylsp` gets configured correctly:

[kak-lsp-works.log](https://github.com/kak-lsp/kak-lsp/files/10148357/kak-lsp.log)

**Comment by krobelus** [comment]
ok I can reproduce the problem with `maxLineLength` being ignored. We need to take a look at what keys pylsp expects because `pylsp.configurationSources = ["flake8"]` definitely works.
As a workaround, you can create this `tox.ini` which is more generally useful anyway.

```ini
[flake8]
max-line-length = 120
```

**Comment by razcore-rad** [comment]
Sure I know the workarounds, but that means that you'll have to use individual configurations for each plugin and I'd rather not, plus I like to have global configs. It's not just about `flake8`

**Comment by razcore-rad** [comment]
Also, I think it's `maxLineLength`, not `max-line-legth` in the `pylsp` plugin config.

**Comment by krobelus** [comment]
for me it fails even if the server does send `didChangeConfiguration`

I found the issue on my end: the warning comes from `pycodestyle`, not `flake8`

```json
      {
        "source": "pycodestyle",
        "range": {
          "start": {
            "line": 11,
            "character": 79
          },
          "end": {
            "line": 11,
            "character": 113
          }
        },
        "message": "E501 line too long (112 > 79 characters)",
        "code": "E501",
        "severity": 2
      },
```

so the fix for me is to use

```toml
pylsp.configurationSources = ["flake8"]
pylsp.plugins.pycodestyle.maxLineLength = 500
```

this works for me 100% of the time.
