### ISSUE TITLE
Broken window/showMessageRequest after upgrading toml from 0.5.6 to 0.8.8

### ISSUE THREAD

**Issue by igor-ramazanov** [kak-lsp/kak-lsp#707]
[This commit](https://github.com/kak-lsp/kak-lsp/commit/bc5ee88a65d2ecb0758c3972c997bbfd49fb355c) broke the `window/showMessageRequest`:

```toml
[package]
name = "kak-lsp-reproduce-toml-bug"
version = "1.0.0"

[dependencies]
toml = "0.5.6"
jsonrpc-core = "18.0.0"
```

```rust
fn main() {
    println!(
        "{:?} {:?} {:?}",
        toml::to_string(&jsonrpc_core::Id::Null),
        toml::to_string(&jsonrpc_core::Id::Num(2)),
        toml::to_string(&jsonrpc_core::Id::Str("2x".to_string()))
    );
}
```

Prints:
```console
$ cargo run 2>/dev/null
Err(UnsupportedType) Ok("2") Ok("\"2x\"")
```

While `toml = 0.8.8`:
```console
$ cargo run 2>/dev/null
Err(Error { inner: UnsupportedType(Some("unit")) }) Err(Error { inner: UnsupportedType(None) }) Err(Error { inner: UnsupportedType(None) })
```
